# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmessage',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
